common:
  json_duplicate_or_invalid_format:
    code: 1000
    localization:
      en: "Json field duplicate or invalid format. Please try again"
      th: "Json มีคีย์ซ้ำกันหรือรูปแบบฟอร์เมตผิด กรุณาลองใหม่อีกครั้ง"

  invalid_username:
    code: 1001
    localization:
      en: "Sorry, your username is incorrect. Please try again"
      th: "ขออภัย เลขบัตรประชาชนของคุณไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

  invalid_password:
    code: 1002
    localization:
      en: "Sorry, your password is incorrect. Please try again"
      th: "ขออภัย รหัสผ่านของคุณไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

  invalid_current_password:
    code: 1003
    localization:
      en: "Sorry, your current password is incorrect. Please try again"
      th: "ขออภัย รหัสผ่านปัจจุบันของคุณไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง"

  invalid_permission_role:
    code: 1004
    localization:
      en: "Sorry,Your permission cannot do the transaction. Please try again"
      th: "ขออภัย สิทธิ์ของคุณไม่สามารถทำรายการดังกล่าวได้ กรุณาลองใหม่อีกครั้ง"

  user_not_found:
    code: 1005
    localization:
      en: "Sorry, user not found. Please try again."
      th: "ขออภัย ไม่พบข้อมูลผู้ใช้งาน กรุณาลองใหม่อีกครั้ง"

  duplicate_email:
    code: 200001
    localization:
      en: "Email already existing. Please use a difference email."
      th: "บัญชีอีเมลล์นี้มีผู้ใช้งานแล้ว กรุณาเปลี่ยนบัญชีอีเมลล์ใหม่"

  duplicate_user:
    code: 200002
    localization:
      en: "This user already existing."
      th: "บัญชีนี้มีผู้ใช้งานแล้ว"
  
  duplicate_cid:
    code: 200003
    localization:
      en: "This cid already existing."
      th: "เลขประจำตัวประชาชนนี้มีผู้ใช้งานแล้ว"

# These are what we response to our internal services
internal:
  success:
    code: 0
    localization:
      en: "Success"
      th: "สำเร็จ"

  general:
    code: 400
    localization:
      en: "System cannot process this request at the moment. Please try again later"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  bad_request:
    code: 400
    localization:
      en: "System cannot process this request at the moment. Please try again later"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  connection_error:
    code: 500
    localization:
      en: "Connection error. Please try again"
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  database_not_found:
    code: 404
    localization:
      en: "Database not found. Please try again"
      th: "ขออภัย ไม่พบข้อมูลในระบบ กรุณาลองใหม่อีกครั้ง"

  unauthorized:
    code: 401
    localization:
      en: "The system does not allow you to access the request. Please try again later"
      th: "ขออภัย ระบบไม่อนุญาตให้คุณเข้าถึงการร้องขอได้ กรุณาลองใหม่อีกครั้ง"